playbook_version: 3.0.0

# ########## Main params ##########
#version
branch: HEAD
#base
contact_email: will@be.overriden
domain: will-be-overriden.by.hostvars
domains:
  tools: 'tools.{{domain}}'
  grafana: 'tools.{{domain}}'
#user
support_user: '0x011'
support_key_file: './public_keys/support.pub'
support_key: "{{ lookup('file', support_key_file) }}"
#dirs
home_dir: '/srv/platform'
data_dir: '{{home_dir}}/data'
dirs:
  kernel_custom_config: "{{data_dir}}/kernel_custom_config"
  kernel: "{{home_dir}}/kernel"
  band_collection: "{{home_dir}}/images/band_collection"
  band: "{{home_dir}}/images/band_base"
  grafana_data: "{{home_dir}}/grafana"
  splash: "{{home_dir}}/splash"
  clickhouse: "/srv/clickhouse"
  clickhouse_tmp: "/srv/clickhouse_tmp"
  redis: "/srv/redis"

ports:
  # services
  band: [10000, 8080]
  kernel: [10001, 8080]
  kernel_ws: [10002, 8082]
  kernel_wss: [10003, 8083]
  heavyload: [10010, 8080]
  # tools
  grafana: [3000, 8080]
  jupyter: [8888, 8080]
  netdata: [19999]
  # servers
  http: [80]
  https: [443]
  openvpn: [8080, 1194]
  redis: [6379, 6379]
  s2svpn: [8079]
  clickhouse: [8123]
  chproxy: [9090, 9090]
  chronograf: [18888]
  influxhttp: [18086]
  influxtsb: [4242]

# ########## Docker ##########
docker_net_name: custom
docker_interface: docker1
docker_net_pattern: 172.16.25.* # will be converted to 172.16.25.0/24
docker_users: 
  - '{{support_user}}'
# calculable
docker_net: "{{docker_net_pattern|ip_p2n}}"
docker_host_ip: "{{docker_net|net_gw}}"
docker_netmask: "{{docker_net|ipaddr('netmask')}}"
docker_network: "{{docker_net|ipaddr('network')}}"

# ########## Common Envs ##########
container_envs:
  REDIS_HOST: "redis"
  REDIS_PORT: "{{ports.redis.1}}"
  REDIS_DB: 2
  BAND_URL: "http://band:8080"
  KERNEL_URL: "http://kernel:8080"
  STATSD_HOST: "{{docker_host_ip}}"

# ########## Clients VPN ##########
covpn_keys_dir: '{{home_dir}}/ovpn_keys'

# ########## Server-server VPN ##########
s2s_vpn_connect: false
s2s_vpn_key: 'ovpn_keys/node{{vpn_id}}.ovpn'
s2s_vpn_net_pattern: 192.168.222.*
s2s_vpn_net: "{{s2s_vpn_net_pattern|ip_p2n}}"
s2s_vpn_host_ip: "{{s2s_vpn_net|net_gw}}"

# ########## Netdata ##########
netdata_from: 'localhost {{docker_net_pattern}} {{s2s_vpn_net}}'
netdata_streaming_from: 'localhost {{docker_net_pattern}} {{s2s_vpn_net}}'
netdata_conf_from: 'localhost'

# ########## Firewall ##########
firewall_rules:
  - { from_ip: '{{docker_net}}'}
  - { to_port: '{{ports.http.0}}'}
  - { to_port: '{{ports.https.0}}'}
  - { to_port: '{{ports.openvpn.0}}'}

# ########## SSL ##########
domains_ssl:
  - email: '{{contact_email}}'
    domains: "{{[domain] + domains.values()|list|unique}}"
  
# ########## Nginx ##########
htpasswd_files:
  tools: []

nginx_vhost_80die:
  - listen 80 default_server
  - server_name _
  - return 301 https://$host$request_uri

nginx_common_params: 
  cert: "{{domain}}"
  root: "{{dirs.splash}}"
  template: "nginx/site.conf.j2"
  domain: "{{domain}}"

nginx_grafana_params: {domain: "{{domains.grafana}}", htpasswd: auth_basic/tools}
nginx_kernel_params: {uploader: yes}

# ########## ClickHouse ##########
clickhouse_db: stats

# ########## CHProxy ##########
# chproxy_allow_from: []
chproxy_allow_from_default:
  - 127.0.0.0/24
  - 172.16.0.0/16
chproxy_def_max_concurrent_queries: 5
chproxy_def_max_queue_size: 100
chproxy_def_max_queue_time: 30s
chproxy_def_max_execution_time: 30s
chproxy_def_allow_cors: true
# chproxy_users: []
chproxy_users_default:
  - name: "{{chproxy_zero_user|default('default')}}"
    password: "{{chproxy_zero_password|default('default')}}"
    to_cluster: "{{'default'}}"
    to_user: "{{'default'}}"
# chproxy_clusters: []
chproxy_clusters_default:
  - name: "{{'default'}}"
    nodes:
      - '{{docker_host_ip}}:{{ports.clickhouse.0}}'
