playbook_version: 3.0.0

# ########## Base ##########
branch: master
names:
  kernel: kernel
  splash: splash
  band: band

contact_email: will@be.overriden
domain: will-be-overriden.by.hostvars
domains:
  tools: 'tools.{{domain}}'
  grafana: 'tools.{{domain}}'

# should override before setup
passwd:
  ch_default: chpass123
  chp_zero: chpass666

support_user: '0x011'
support_key_file: './public_keys/support.pub'
support_key: "{{ lookup('file', support_key_file) }}"
home_dir: '/srv/platform'
data_dir: '{{home_dir}}/data'
dirs:
  kernel_custom_config: "{{data_dir}}/kernel_custom_config"
  grafana_data: "{{home_dir}}/grafana"
  splash: "{{home_dir}}/{{names.splash}}"
  clickhouse: "/srv/clickhouse"
  clickhouse_tmp: "/srv/clickhouse_tmp"

# ports
ports:
  band: 10000
  kernel: 10001
  kernel_ws: 10002
  kernel_wss: 10003
  heavyload: 10010
  #tools
  grafana: 3000
  jupyter: 8888
  netdata: 19999
  openvpn: 8080
  clickhouse: 8123
  chproxy: 9090

# ########## SSL ##########
domains_ssl:
  - email: '{{contact_email}}'
    domains: "{{[domain] + domains.values()|list|unique}}"
# ########## Docker ##########
docker_net_name: custom
docker_interface: docker1
docker_net_pattern: 172.16.25.* # will be converted to 172.16.25.0/24
docker_users: 
  - '{{support_user}}'
# calculable
docker_net: "{{docker_net_pattern|replace('*', '0')}}/{{32 - (docker_net_pattern|regex_findall('(\\*)'))|count * 8}}"
docker_host_ip: "{{docker_net|ipaddr(1)|ipaddr('address')}}"
docker_netmask: "{{docker_net|ipaddr('netmask')}}"
docker_network: "{{docker_net|ipaddr('network')}}"
# ########## Clients VPN ##########
covpn_keys_dir: '{{home_dir}}/ovpn_keys'

# ########## Server-server VPN ##########
s2s_vpn_connect: false
s2s_vpn_net_pattern: 192.168.222.*
s2s_vpn_net: "{{s2s_vpn_net_pattern|replace('*', '0')}}/{{32 - (s2s_vpn_net_pattern|regex_findall('(\\*)'))|count * 8}}"
s2s_vpn_host_ip: "{{s2s_vpn_net|ipaddr(1)|ipaddr('address')}}"

# ########## Netdata ##########
netdata_from: 'localhost {{docker_net_pattern}} {{s2s_vpn_net}}'
netdata_streaming_from: 'localhost {{docker_net_pattern}} {{s2s_vpn_net}}'
netdata_conf_from: 'localhost'

# ########## ClickHouse ##########
clickhouse_db: stats

# ########## ClickHouse Proxy ##########
# chproxy_allow_from: []
chproxy_allow_from_default:
  - 127.0.0.0/24
  - 172.16.0.0/16
chproxy_def_max_concurrent_queries: 5
chproxy_def_max_queue_size: 100
chproxy_def_max_queue_time: 30s
chproxy_def_max_execution_time: 30s
chproxy_def_allow_cors: true
# chproxy_users: []
chproxy_users_default:
  - name: "{{chproxy_zero_user|default('default')}}"
    password: "{{chproxy_zero_password|default('default')}}"
    to_cluster: "{{'default'}}"
    to_user: "{{'default'}}"
# chproxy_clusters: []
chproxy_clusters_default:
  - name: "{{'default'}}"
    nodes:
      - '{{docker_host_ip}}:{{ports.clickhouse}}'

# ########## Mailer config ##########
mailer_subj_key: "Ваши ключи OpenVPN ({{ domain }}) v{{ playbook_version }}"
mailer_subj_snip: "Сниппет для сайта ({{ domain }}) v{{ playbook_version }}"
mailer_enabled: false

# ########## Mailer config ##########
firewall_rules:
  - { from_ip: '{{docker_net}}'}
  - { to_port: '80'}
  - { to_port: '443'}
  - { to_port: '{{ports.openvpn}}'}

# ########## nginx ##########
nginx_auth_basic_files:
  tools: []
#    - dr:$apr1$.aUTart5$SSq.......
# generate using: printf "dr:`openssl passwd -apr1`\n"

nginx_vhost_80die:
  - listen 80 default_server
  - server_name _
  - return 301 https://$host$request_uri

nginx_common_params: 
  cert: "{{domain}}"
  root: "{{dirs.splash}}"
  template: "nginx-site.conf.j2"
  domain: "{{domain}}"

nginx_grafana_params: {domain: "{{domains.grafana}}", htpassw: auth_basic/tools}
nginx_kernel_params: {uploader: yes}

nginx_config_gzip:
  - gzip on
  - gzip_min_length 10240
  - gzip_proxied expired no-cache no-store private auth
  - gzip_types text/plain text/css text/javascript application/javascript application/x-javascript
nginx_ssl_params:
  - ssl_session_cache shared:SSL:10m
  - ssl_session_timeout 10m
  - ssl_prefer_server_ciphers on
  - ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5
  - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
  - ssl_stapling on
  - ssl_stapling_verify on
nginx_http_params_custom:
  - access_log off
  - error_log /var/log/nginx/error.log
  - tcp_nopush on
  - tcp_nodelay on
  - keepalive_timeout 60
  - keepalive_requests 1000
  - access_log "/var/log/nginx/access.log"

# ########## Grafana ##########
grafana_plugins:
  - grafana-clock-panel
  - grafana-simple-json-datasource
  - vertamedia-clickhouse-datasource
  - grafana-piechart-panel
  - petrslavotinek-carpetplot-panel
  - jdbranham-diagram-panel
  - raintank-worldping-app
  - ryantxu-ajax-panel
  - natel-discrete-panel
# use this variable in your private config
# grafana_plugins_custom:
  # - plugin that i want
