playbook_version: 2.1.3
initial_user: root

alco_user: 'alco'
alco_key_file: './public_keys/alco.pub'
alco_home_dir: '/srv/alco'
alco_data_dir: '/srv/alco/data'
alco_data_ch_upload_dir: '{{alco_data_dir}}/ch_upload'
alco_tracker_custom_config_dir: '{{alco_data_dir}}/custom_tracker_config'

# Docker
alco_docker_net_name: alconet
alco_docker_interface: docker1
alco_docker_net: 172.16.25.0/24
alco_docker_net_pattern: 172.16.25.*
alco_docker_ip: "{{alco_docker_net|ipaddr(1)|ipaddr('address')}}"
alco_docker_netmask: "{{alco_docker_net|ipaddr('netmask')}}"
alco_docker_network: "{{alco_docker_net|ipaddr('network')}}"
alco_docker_user: '{{alco_user}}'

# OVPN
alco_ovpn_keys_dir: '{{alco_home_dir}}/ovpn_keys'
alco_ovpn_port: 8080

# internal VPN (for supported servers)
alco_internal_vpn_connect: false
alco_internal_vpn_net: 192.168.222.0/24
alco_internal_vpn_net_pattern: 192.168.222.*
alco_internal_vpn_host_ip: "{{alco_internal_vpn_net|ipaddr(1)|ipaddr('address')}}"

# netdata
alco_netdata_from: 'localhost {{alco_docker_net_pattern}}'
alco_netdata_streaming_from: 'localhost {{alco_docker_net_pattern}}'


# ClickHouse
alco_db_name: alco
alco_db_pass: alco
alco_ch_port: 8123
alco_ch_proxy_port: 9090

# Email config
alco_email_subj_key: "Ваши ключи OpenVPN ({{ tracker_domain }}) v{{ playbook_version }}"
alco_email_subj_snip: "Сниппет для сайта ({{ tracker_domain }}) v{{ playbook_version }}"
alco_email_enabled: false

# Tracker
alco_tracker_path: '{{alco_home_dir}}/alco-tracker'
alco_trackers_version: master
alco_tracker_log_level: info

# base firewall rules
alco_firewall_rules:
  - { from_ip: '{{alco_docker_network}}/{{alco_docker_netmask}}'}
  - { to_port: '80'}
  - { to_port: '443'}
  - { to_port: '{{alco_ovpn_port}}'}


# nginx params
alco_nginx_ssl_params:
  - ssl_session_cache shared:SSL:10m
  - ssl_session_timeout 10m
  - ssl_prefer_server_ciphers on
  - ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5
  - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
  - ssl_stapling on
  - ssl_stapling_verify on

alco_nginx_http_params:
  - access_log off
  - error_log /var/log/nginx/error.log
  - tcp_nopush on
  - tcp_nodelay on
  - keepalive_timeout 60
  - keepalive_requests 1000
  - access_log "/var/log/nginx/access.log"

alco_vhost_default:
  - listen 80 default_server
  - server_name _
  - return 301 https://$host$request_uri

alco_nginx_vhost_def:
  - listen 443 ssl http2
  - add_header 'Cache-Control' 'no-store, must-revalidate'
  - expires off


alco_nginx_node_loc:
  - location / { try_files $uri $uri/index.html @node; }
  - location @node {
      proxy_redirect   off;
      proxy_buffering  off;
      proxy_set_header Host             $host;
      proxy_set_header X-Real-IP       $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass       http://alco-tracker;
    }

alco_nginx_vhost_tracker:
  - server_name {{tracker_domain}}
  - root {{alco_home_dir}}/alco-tracker/public
  - ssl_certificate_key /etc/letsencrypt/live/{{tracker_domain}}/privkey.pem
  - ssl_certificate     /etc/letsencrypt/live/{{tracker_domain}}/fullchain.pem
  - ssl_trusted_certificate /etc/letsencrypt/live/{{tracker_domain}}/chain.pem

alco_upstream_tracker: 'upstream alco-tracker { server {{alco_docker_ip}}:8081 weight=10; }'

alco_config_gzip:
  - gzip on
  - gzip_min_length 10240
  - gzip_proxied expired no-cache no-store private auth
  - gzip_types text/plain text/css text/javascript application/javascript application/x-javascript

alco_vhost_tracker: '{{alco_nginx_vhost_def + alco_nginx_vhost_tracker + alco_nginx_node_loc}}'

alco_nginx_sites:
  default: '{{alco_vhost_default}}'
  tracker: '{{alco_vhost_tracker}}'

alco_nginx_upstreams:
  - '{{alco_upstream_tracker}}'


# SSL

alco_ssl_certs:
  - email: '{{contact_email}}'
    domains:
      - '{{tracker_domain}}'



# Migrations

ch_path: '{{alco_tracker_path}}/clickhouse_schema'
ch_operations:

#  # Чистый SQL запрос
#  - type: query
#    query: 'SELECT count() FROM events'
#
# Миграция из локального файла
#  - type: local_migration
#    file: 2-migration-ren-table.yml

#   Таблица с миграций
  - type: query_file
    file: '{{ch_path}}/table_migrations.sql'


#   Файл миграции в репе трекера
  - type: migration
    file: '{{ch_path}}/2-migration-ren-table.yml'
##
##  - type: query_file
##    file: '{{ch_path}}/table_migrations.sql'
