- name: Configuring UFW rules
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - { rule: 'allow', port: '22', proto: 'tcp' }
    - { rule: 'allow', port: '80', proto: 'tcp' }
    - { rule: 'allow', port: '443', proto: 'tcp' }
    - { rule: 'allow', port: '8080', proto: 'tcp' }
  become: yes

- name: Configuring UFW defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  become: yes

- name: Configuring UFW subnets
  ufw:
    rule: allow
    src: '{{ item }}'
  with_items:
    - '{{alco_docker_net}}'
  become: yes

- name: Enabling UFW
  ufw: state=enabled
  become: yes
