# https://github.com/jdauphant/ansible-role-nginx
# https://github.com/jaywink/ansible-letsencrypt
---
- name : Installing Alcolytics
  hosts: all
  remote_user: '{{alco_user}}'
  tasks:
    - import_role:
        name: alco-openvpn-server
      vars:
        ovpn_keys_dir: '{{ovpn_keys_dir}}'
        ovpn_docker_net_name: '{{alco_docker_net_name}}'
        ovpn_docker_network: '{{alco_docker_network}}'
        ovpn_docker_netmask: '{{alco_docker_netmask}}'
      tags: ['ovpn']

    - import_role:
        name: alco-chproxy
      vars:
        chproxy_docker_net_name: '{{alco_docker_net_name}}'
        chproxy_docker_bind_addr: '{{alco_docker_ip}}'
        chproxy_docker_http_allow_net: '{{alco_docker_net}}'
        chproxy_ch_addr: '{{alco_docker_ip}}'
      tags: ['chproxy']

    - import_role:
        name: alco-services
      vars:
        alco_service_bind_addr: '{{alco_docker_ip}}'
        alco_service_net_name: '{{alco_docker_net_name}}'
      tags: ['services']

    - import_role:
        name: alco-grafana
      vars:
        gragana_docker_net_name: '{{alco_docker_net_name}}'
        grafana_docker_bind_addr: '{{alco_docker_ip}}'
      tags: ['grafana']

    - import_role:
        name: alco-anaconda
      vars:
        anaconda_docker_net_name: '{{alco_docker_net_name}}'
        anaconda_docker_bind_addr: '{{alco_docker_ip}}'
      tags: ['anaconda']

    - import_role:
        name: alco-tracker
      vars:
        alco_service_bind_addr: '{{alco_docker_ip}}'
        alco_service_net_name: '{{alco_docker_net_name}}'
        alco_service_path: '{{alco_tracker_path}}'
        alco_service_version: '{{alco_tracker_branch}}'
      tags: ['tracker']

    - import_role:
        name: alco-clickhouse-ops
      vars:
        alco_ch_ops_list: '{{ch_operations}}'
        alco_ch_ops_host: '127.0.0.1'
        alco_ch_ops_db: '{{alco_db_name}}'
      tags: ['ch-schema']
