---
- name: Preparing system for Alcolytics
  hosts: all
  remote_user: '{{ initial is defined|ternary(initial_user is defined|ternary(initial_user, "root"), alco_user) }}'
  become: yes
  tasks:
    - import_role:
        name: alco-common
      vars:
      tags: ['common']

    - import_role:
        name: alco-letsencrypt
      vars:
        letsencrypt_domains_groups:
          - email: '{{contact_email}}'
            domains: ['{{tracker_domain}}']
        letsencrypt_pause_services: ['nginx']
      tags: ['ssl']

    - import_role:
        name: jdauphant.nginx
      vars:
        nginx_official_repo: yes
        keep_only_specified: yes
        nginx_http_params: '{{alco_nginx_http_params}}'
        nginx_sites:
          default: '{{alco_vhost_default}}'
          tracker: '{{alco_vhost_tracker}}'
        nginx_configs:
          gzip: '{{alco_config_gzip}}'
          upstream:
            - '{{alco_upstream_tracker}}'
      tags: ['nginx']

    - import_role:
        name: alco-docker
      tags: ['docker']

    - import_role:
        name: alco-clickhouse
      vars:
        clickhouse_networks_default: ["::1", "127.0.0.1", "{{ alco_docker_net }}"]
        clickhouse_dbs_custom: [{name: '{{alco_db_name}}'}]
        clickhouse_path_data: "/srv/clickhouse/"
        clickhouse_path_tmp: "/srv/clickhouse/tmp/"
      tags: ['clickhouse']

    - import_role:
        name: alco-netdata
      vars:
      tags: ['netdata']
