---
- name: Installing alcolytics
  hosts: all
  remote_user: "{{initial_user|default('root')}}"
  become: yes
  tasks:
    - import_role:
        name: dr.server
      vars:
        drs_user: '{{alco_user}}'
        drs_pub_key_file: '{{alco_key_file}}'
      tags: ['base']

    - import_role:
        name: dr.exposeur
      vars:
        expo_reset_ufw: true
        expo_rules: '{{alco_firewall_rules + alco_priv_ufw_rules|default([]) + alco_group_ufw_rules|default([])}}'
        expo_expose_rules: '{{alco_expose_rules|default([]) + alco_group_expose_rules|default([])}}'
      tags: ['firewall']

    - import_role:
        name: dr.openvpn-client
      vars:
        openvpnc_key: '{{alco_internal_vpn_key|default(omit)}}'
      when: alco_internal_vpn_connect == True and vpn_id is defined
      tags: ['ovpn-client']

    - import_role:
        name: dr.letsencrypt
      vars:
        letsencrypt_domains_groups: '{{alco_ssl_certs}}'
        letsencrypt_pause_services: ['nginx']
      tags: ['ssl']

    - import_role:
        name: jdauphant.nginx
      vars:
        nginx_official_repo: yes
        keep_only_specified: yes
        nginx_http_params: '{{alco_nginx_http_params}}'
        nginx_sites: '{{alco_nginx_sites}}'
        nginx_configs:
          gzip: '{{alco_config_gzip}}'
          upstream: '{{alco_nginx_upstreams}}'
          ssl: '{{alco_nginx_ssl_params}}'
      tags: ['nginx']

    - import_role:
        name: alco-docker
      tags: ['docker']

    - import_role:
        name: alco-clickhouse
      vars:
        clickhouse_users_custom: '{{ch_users|default([])}}'
        clickhouse_networks_default: ["::1", "127.0.0.1", "{{ alco_docker_net }}"]
        clickhouse_dbs_custom: [{name: '{{alco_db_name}}'}]
        clickhouse_path_data: "/srv/clickhouse/"
        clickhouse_path_tmp: "/srv/clickhouse/tmp/"
      tags: ['clickhouse']

    - import_role:
        name: dr.netdata
      vars:
        netdata_allow_dashboard_from: '{{alco_netdata_from}}'
        netdata_allow_badges_from: '{{alco_netdata_from}}'
        netdata_allow_conf_from: '{{alco_netdata_from}}'
        netdata_allow_connections_from: '{{alco_netdata_streaming_from}}'
        netdata_allow_streaming_from: '{{alco_netdata_streaming_from}}'
      tags: ['netdata']

# from platform file

    - import_role:
        name: alco-openvpn-server
      vars:
        ovpn_keys_dir: '{{alco_ovpn_keys_dir}}'
        ovpn_docker_net_name: '{{alco_docker_net_name}}'
        ovpn_docker_network: '{{alco_docker_network}}'
        ovpn_docker_netmask: '{{alco_docker_netmask}}'
        ovpn_port: '{{alco_ovpn_port}}'
      tags: ['ovpn']

    - import_role:
        name: alco-chproxy
      vars:
        chproxy_docker_attach_net: '{{alco_docker_net_name}}'
        chproxy_docker_expose: '{{alco_docker_ip}}:9090'
        chproxy_build_root: '{{alco_home_dir}}'
        chproxy_def_user: alco
        chproxy_def_password: alco
        chproxy_def_node: '{{alco_docker_ip}}:8123'
      tags: ['chproxy']

    - import_role:
        name: alco-services
      vars:
        alco_service_bind_addr: '{{alco_docker_ip}}'
        alco_service_net_name: '{{alco_docker_net_name}}'
        alco_service_clone_to: '{{alco_home_dir}}'
      tags: ['services']

    - import_role:
        name: alco-grafana
      vars:
        gragana_docker_net_name: '{{alco_docker_net_name}}'
        grafana_docker_bind_addr: '{{alco_docker_ip}}'
      tags: ['grafana']

    - import_role:
        name: alco-anaconda
      vars:
        anaconda_docker_data_dir: '{{alco_data_dir}}'
        anaconda_docker_net_name: '{{alco_docker_net_name}}'
        anaconda_docker_bind_addr: '{{alco_docker_ip}}'
        anaconda_docker_memory_limit: '2g' #todo: use half of available size
      tags: ['anaconda']

    - import_role:
        name: alco-tracker
      vars:
        alco_service_bind_addr: '{{alco_docker_ip}}'
        alco_service_net_name: '{{alco_docker_net_name}}'
        alco_service_path: '{{alco_tracker_path}}'
        alco_service_version: '{{alco_trackers_version|default(omit)}}'
        alco_service_upload_store: '{{alco_data_ch_upload_dir}}'
        alco_service_custom_configs_dir: '{{alco_tracker_custom_config_dir}}'
        alco_service_log_level: '{{alco_tracker_log_level}}'
      tags: ['tracker']

    - import_role:
        name: alco-clickhouse-ops
      vars:
        alco_ch_ops_list: '{{ch_operations|default([]) + ch_operations_custom|default([])}}'
        alco_ch_ops_host: '127.0.0.1'
        alco_ch_ops_db: '{{alco_db_name}}'
      tags: ['schema']
