---
- name: Installing platform
  hosts: rockstat
  become: yes
  vars_files:
    - vars/config.yml
  tasks:

    - block:
      - include_role:
          name: dr.server
        vars:
          drs_setup_user: yes
          drs_user: '{{support_user}}'
          drs_home_dir: "{{home_dir}}"
          drs_pub_key_file: '{{support_key_file}}'
          drs_disable_ipv6: "{{disable_ipv6}}"
      when: 'setup_server == True'
      tags: ['os', 'system']


    - block:
      - include_role:
          name: dr.docker
        vars:
          drd_users:
          - "{{support_user}}"
          drd_create_network: yes
          drd_version: edge
          drd_net_name: '{{docker_net_name}}'
          drd_bind_ip: "{{docker_host_ip}}"
          drd_interface: '{{docker_interface}}'
          drd_net: '{{docker_net}}'
          drd_mtu: '1400'
      tags: ['docker', 'system']


    - block:
      - include_role:
          name: dr.exposeur
        vars:
          expo_reset_ufw: true
          expo_rules: '{{firewall_rules + host_firewall_rules|default([]) + group_firewall_rules|default([])}}'
          expo_expose_rules: '{{expose_rules|default([]) + host_expose_rules|default([]) + group_expose_rules|default([])}}'
      tags: ['firewall', 'system']

    - block:
      - debug:
          msg: "docker_net_name:{{docker_net_name}}, docker_ipnetwork:{{docker_ipnetwork}} docker_netmask:{{docker_netmask}} "
      - name: Creating vpn keys dir
        file:
          state: directory
          path: "{{dirs.ovpnkeys}}"
      - include_role:
          name: alco-openvpn-server
        vars:
          ovpn_domain: "{{domain}}"
          ovpn_keys_dir: '{{dirs.ovpnkeys}}'
          ovpn_docker_net_name: '{{docker_net_name}}'
          ovpn_docker_network: '{{docker_ipnetwork}}'
          ovpn_docker_netmask: '{{docker_netmask}}'
          ovpn_port: '{{ports.openvpn.0}}'
      tags: ['ovpn', 'system']

    - block:
      - include_role:
          name: dr.letsencrypt
        vars:
          letsencrypt_domains_groups: '{{domains_ssl}}'
          letsencrypt_pause_services: ['nginx']
      when: "setup_ssl == True"
      tags: ['ssl', 'system']


    - block:
      - name: Loading nginx users
        include_vars:
          file: "{{ item }}"
          name: users_data
        with_first_found:
          - "files/{{inventory_hostname }}/users.yml"
          - "files/users.yml"
          - "files/empty.yml"
      - include_role:
          name: jdauphant.nginx
        vars:
          nginx_official_repo: no
          keep_only_specified: yes
          nginx_http_params: '{{cfg_nginx_http_params}}'
          nginx_sites: "{{ngx_sites}}"
          nginx_auth_basic_files:
            common: "{{users_data.users|default([])}}"
          nginx_configs:
            upgrade: '{{nginx_protoup}}'
            gzip: '{{cfg_nginx_gzip_params}}'
            proxy: '{{cfg_nginx_proxy_params}}'
            upstream: '{{ngx_upstreams}}'
            ssl: '{{cfg_nginx_ssl_params}}'
      when: "setup_nginx == True"
      tags: ['nginx', 'system']


    - block:
      - include_role:
          name: dr.netdata
        vars:
          drn_allow:
            dashboard_from: "*"
            badges_from: "*"
            conf_from: "*"
            connections_from: "*"
            streaming_from: "*"
          drn_stream: '{{netdata_stream_config|default({})}}'
          drn_backend: '{{netdata_backend_config|default({})}}'
          drn_bind_to: "{{if_inner}}"
      tags: ['netdata', 'system']


    - block: 
      - include_role:
          name: AlexeySetevoi.clickhouse
        vars:
          nets: 
          ifaces: 
          clickhouse_users_custom: '{{ch_users|default([])}}'
          clickhouse_listen_host_default: "{{ ['127.0.0.1'] + disable_ipv6|ternary([],['::1']) }}"
          clickhouse_listen_host_custom: "{{ [ if_inner ] }}"
          clickhouse_networks_default: "{{ ['127.0.0.1', docker_net] + disable_ipv6|ternary([],['::1']) }}"
          clickhouse_dbs_custom: [{name: '{{ch_db}}'}]
          clickhouse_path_data: "{{dirs.clickhouse}}"
          clickhouse_path_tmp: "{{dirs.clickhouse_tmp}}"
      tags: ['clickhouse', 'system']


    - block:
      - name: CHProxy setup
        debug: msg="role begin"
      - include_role: 
          name: chproxy
        vars:
          chproxy_docker_bind: "{{if_inner}}:{{ports.chproxy.0}}:{{ports.chproxy.1}}"
          chproxy_def_node: "{{if_inner}}:{{ports.clickhouse.0}}"
          chproxy_clusters: "{{hst_chproxy_clusters|default([])}}"
          chproxy_docker_net: "{{docker_net_name}}"
          chproxy_users: "{{hst_chproxy_users|default([])}}"
          chproxy_allowed_networks: "{{chproxy_allow_from|default([])}}"
          chproxy_build_path: "{{build_dir}}/chproxy"
      tags: ['chproxy', '3rdparty']


    - name: Redis setup
      block:
      - include_role:
          name: dr.docker-container
        vars:
          drdc_name: "redis"
          drdc_image: "redis:4-alpine"
          drdc_network: '{{docker_net_name}}'
          drdc_hosts: "{{docker_etc_hosts}}"
          drdc_memory_limit: '200m'
          drdc_volumes: ["{{dirs.redis}}:/data"]
          drdc_ports: ["{{if_inner}}:{{ports.redis.0}}:{{ports.redis.1}}"]
      tags: ['redis', 'system', 'docker', 'docker-container']


    - name: Logspout with Loggly streaming
      block:
      - include_role:
          name: dr.docker-container
        vars:
          drdc_name: "logspout"
          drdc_image: "gliderlabs/logspout"
          drdc_network: '{{docker_net_name}}'
          drdc_hosts: "{{docker_etc_hosts}}"
          drdc_memory_limit: '200m'
          drdc_cmd: syslog+tcp://logs-01.loggly.com:514
          drdc_volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          drdc_env:
            SYSLOG_STRUCTURED_DATA: "{{loggly_api_key}}@41058 tag=\"Logspout\""
            SYSLOG_HOSTNAME: "{{hostname}}"
      when: 'loggly_api_key is defined'
      tags: ['logspout', 'system', 'docker', 'docker-container']


    - block:
      - name: Anaconda setup
        debug: msg="bind to {{if_inner}}:{{ports.jupyter.0}}:{{ports.jupyter.1}}"
      - include_role:
          name: dr.docker-container
        vars:
          conda_list: "{{jup_with_conda_def + jup_with_conda}}"
          pip_list: "{{jup_with_pip_def + jup_with_pip}}"
          cmd_parts:
            - "{{conda_list|length > 0 and ('conda install -y ' + conda_list|join(' ') + ' && ') or ''}}"
            - "{{pip_list|length > 0 and ('pip install ' + pip_list|join(' ') + ' && ') or ''}}"
            - "/opt/conda/bin/conda install jupyter -y --quiet && "
            - "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks"
            - "--ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.allow_origin='*'"
          drdc_name: 'anaconda'
          drdc_image: "continuumio/anaconda3"
          drdc_network: '{{docker_net_name}}'
          drdc_hosts: "{{docker_etc_hosts}}"
          drdc_memory_limit: '{{anaconda_mem_limit}}'
          drdc_cmd: "/bin/bash -c \"{{cmd_parts|join(' ')}}\""
          drdc_labels: "{{docker_band_lbls}}"
          drdc_volumes: 
            - '{{dirs.notebooks}}:/opt/notebooks'
          drdc_ports: ["{{if_inner}}:{{ports.jupyter.0}}:{{ports.jupyter.1}}"]
      when: 'setup_jupyter == True'
      tags: ['anaconda', '3rdparty', 'docker', 'docker-container']


    - block:
      - name: Creating Grafana datadir
        file:
          state: directory
          path: "{{dirs.grafana_data}}"
          owner: 472 # grafana container ids
          group: 472
      - include_role:
          name: dr.docker-container
        vars:
          drdc_name: 'grafana'
          drdc_image: "grafana/grafana"
          drdc_network: '{{docker_net_name}}'
          drdc_hosts: "{{docker_etc_hosts}}"
          drdc_env:
            GF_INSTALL_PLUGINS: "{{(grafana_plugins_custom|default([]) + grafana_plugins)|join(',')}}"
            GF_AUTH_BASIC_ENABLED: 'true'
            GF_ALLOW_SIGN_UP: 'false'
            GF_AUTO_ASSIGN_ORG: yes
            GF_AUTO_ASSING_ORG_ROLE: Editor
            GF_AUTH_PROXY_ENABLED: 'true'
            GF_AUTH_PROXY_HEADER_NAME: yes
            GF_AUTH_PROXY_AUTO_SIGN_UP: 'true'
            # GF_SECURITY_ADMIN_PASSWORD: secret
          drdc_memory_limit: '200m'
          drdc_labels: "{{docker_band_lbls}}"
          drdc_volumes:
            - '{{dirs.grafana_data}}:/var/lib/grafana'
          drdc_ports:
            - "{{if_inner}}:{{ports.grafana.0}}:{{ports.grafana.1}}"
      tags: ['grafana', '3rdparty', 'docker', 'docker-container']


    - block:
      - include_role:
          name: dr.static-service
        vars:
          dr_name: splash
          dr_dir: '{{dirs.splash}}'
          dr_repo: https://github.com/rockstat/splash
      tags: ['splash', 'platform']


    - block:
      - name: Building band-base-py image
        include_role:
          name: dr.docker-container
        vars:
          drdc_name: band-base-py
          drdc_image: 'rst/band-base-py'
          drdc_dir: '{{dirs.band}}'
          drdc_repo: "https://github.com/rockstat/band"
          drdc_run_container: no
      - name: Building dire—Åtor service
        include_role:
          name: dr.docker-container
        vars:
          env:
            PORT: "{{ports.band.1}}"
            IMAGES_PATH: /images
          drdc_image: 'rst/band-director'
          drdc_name: 'director'
          drdc_dir: '{{dirs.band_collection}}'
          drdc_rel_path: '/director'
          drdc_repo: "https://github.com/rockstat/band-services"
          drdc_network: '{{docker_net_name}}'
          drdc_hosts: "{{docker_etc_hosts}}"
          drdc_labels: "{{docker_band_lbls}}"
          drdc_env: "{{env|combine(containers_env)}}"
          drdc_memory_limit: '300m'
          drdc_volumes:
            - "{{dirs.band_collection}}:/images/band_collection:ro"
            - "{{dirs.director_data}}:/data" # containers configs
            - "{{dirs.band}}:/images/band_base_py:ro"
            - "{{dirs.user_images}}:/images/user:cached"
            - "/var/run/docker.sock:/var/run/docker.sock"
          drdc_ports:
            - "{{if_inner}}:{{ports.band.0}}:{{ports.band.1}}"
      tags: ['band', 'platform', 'docker', 'docker-container']


    - block:
      - name: Creating User Images Directory
        file: state=directory path={{dirs.user_images}} owner=473 group=473
      - name: Creating User Workspace Directory
        file: state=directory path={{dirs.workspace}} owner=473 group=473
      - include_role:
          name: dr.docker-container
        vars:
          drdc_name: 'theia'
          drdc_dir: "{{build_dir}}/theia"
          drdc_repo: "https://github.com/rockstat/theia-build.git"
          drdc_labels: "{{docker_band_lbls}}"
          drdc_network: '{{docker_net_name}}'
          drdc_hosts: "{{docker_etc_hosts}}"
          drdc_memory_limit: '2g'
          drdc_nocache: "{{nocache is defined}}"
          drdc_volumes:
            - "{{dirs.workspace}}:{{workspace}}/:cached"
            - "{{dirs.user_images}}:{{workspace}}/my_images:cached"
            - "{{dirs.band_collection}}/.skeletons:{{workspace}}/sources/skeletons_ro:ro"
            - "{{dirs.band_collection}}:{{workspace}}/sources/band_images_ro:ro"
          drdc_ports: ["{{if_inner}}:{{ports.theia.0}}:{{ports.theia.1}}"]
      - name: Copying bootstrap files
        command: 'cp -nR {{build_dir}}/theia/bootstrap/.theia {{dirs.workspace}}/'
      vars:
        workspace: "/home/theia/project"
      when: 'setup_theia == True'
      tags: ['theia', 'platform', 'band', 'docker', 'docker-container']


    - name: Frontier setup
      block:
      - include_role:
          name: dr.docker-container
        vars:
          env: {}
          drdc_name: 'frontier'
          drdc_image: 'rst/frontier'
          drdc_dir: "{{build_dir}}/frontier"
          drdc_repo: "https://github.com/rockstat/frontier"
          drdc_network: '{{docker_net_name}}'
          drdc_hosts: "{{docker_etc_hosts}}"
          drdc_env: "{{env|combine(containers_env)}}"
          drdc_labels: "{{docker_band_lbls}}"
          drdc_memory_limit: '300m'
          drdc_volumes:
            - "{{dirs.frontier_custom_config}}:/app/config/custom"
          drdc_ports:
            - "{{if_inner}}:{{ports.frontier.0}}:{{ports.frontier.1}}"
      tags: ['frontier', 'platform', 'rockme', 'docker', 'docker-container']

    - name: Clickhouse writer
      block:
      - include_role:
          name: clickhouse-maintain
        vars:
          role_ops_db: "{{ch_db}}"
          role_migrations_path: clickhouse_migrations
        tags: ['never', 'chmigrate']
      - include_role:
          name: dr.docker-container
        vars:
          env: {}
          drdc_name: 'chwriter'
          drdc_image: 'rst/chwriter'
          drdc_dir: "{{build_dir}}/chwriter"
          drdc_repo: "https://github.com/rockstat/chwriter"
          drdc_network: '{{docker_net_name}}'
          drdc_hosts: "{{docker_etc_hosts}}"
          drdc_env: "{{env|combine(containers_env)}}"
          drdc_labels: "{{docker_band_lbls}}"
          drdc_memory_limit: '300m'
          drdc_volumes:
            - "{{dirs.chwriter_custom_config}}:/app/config/custom"
            - "{{dirs.chwriter_emergency}}:/app/emergency"
      tags: ['chwriter', 'chmigrate', 'platform', 'rockme', 'docker', 'docker-container']

    - block:
      - include_role:
          name: dr.docker-container
        vars:
          drdc_name: 'heavyload'
          drdc_network: '{{docker_net_name}}'
          drdc_hosts: "{{docker_etc_hosts}}"
          drdc_pull: false
          drdc_env:
            WEBHOOK: "{{containers_env.FRONTIER_URL}}/wh/0/upload/notify"
          drdc_repo: https://github.com/rockstat/heavyload
          drdc_labels: "{{docker_band_lbls}}"
          drdc_dir: "{{build_dir}}/heavyload"
          drdc_memory_limit: '100m'
          drdc_ports:
            - "{{if_inner}}:{{ports.heavyload.0}}:{{ports.heavyload.1}}"
          drdc_volumes:
            - "{{dirs.uploads}}:/go/src/heavyload/upload"
      tags: ['heavyload', 'platform', 'docker', 'docker-container']

    # - import_tasks: extensions/metrics_server.yml
    #   when: 'metrics_server == True'

    # - import_role:
    #     name: dr.openvpn-client
    #   vars:
    #     openvpnc_key: '{{s2s_vpn_key}}'
    #   when: s2s_vpn_connect is defined and s2s_vpn_connect == True and vpn_id is defined
    #   tags: ['s2s-ovpn-client', 's2s-ovpn']

