---
- name: Installing platform
  hosts: rockstat
  become: yes
  vars_files:
    - vars/config.yml
  tasks:

    # - debug: msg={{ports.band.1}}
    - import_role:
        name: dr.server
      vars:
        drs_setup_user: yes
        drs_user: '{{support_user}}'
        drs_pub_key_file: '{{support_key_file}}'
      tags: ['os']

    - import_role:
        name: dr.docker
      vars:
        drd_users:
        - "{{support_user}}"
        drd_create_network: yes
        drd_net_name: '{{docker_net_name}}'
        drd_bind_ip: "{{docker_host_ip}}"
        drd_interface: '{{docker_interface}}'
        drd_net: '{{docker_net}}'
      tags: ['docker']
      become: yes

    - import_role:
        name: dr.exposeur
      vars:
        expo_reset_ufw: true
        expo_rules: '{{firewall_rules + priv_firewall_rules|default([]) + group_firewall_rules|default([])}}'
        expo_expose_rules: '{{expose_rules|default([]) + priv_expose_rules|default([]) + group_expose_rules|default([])}}'
      tags: ['firewall']

    - import_role:
        name: dr.letsencrypt
      vars:
        letsencrypt_domains_groups: '{{domains_ssl}}'
        letsencrypt_pause_services: ['nginx']
      tags: ssl

    - import_role:
        name: dr.static-service
      vars:
        dr_name: splash
        dr_dir: '{{dirs.splash}}'
        dr_repo: https://github.com/rockstat/splash
      tags: splash

    - import_role:
        name: jdauphant.nginx
      vars:
        nginx_official_repo: yes
        keep_only_specified: yes
        nginx_http_params: '{{cfg_nginx_http_params}}'
        nginx_sites:
          default: "{{ nginx_vhost_80die }}"
          kernel: "{{ nginx_common_params|combine(nginx_kernel_params) }}"
          grafana: "{{ nginx_common_params|combine(nginx_grafana_params) }}"
        nginx_auth_basic_files: '{{htpasswd_files}}'
        nginx_configs:
          gzip: '{{cfg_nginx_gzip_params}}'
          upstream:
            - 'upstream kernel { server {{docker_host_ip}}:{{ports.kernel.0}} weight=10; }'
            - 'upstream heavyload { server {{docker_host_ip}}:{{ports.heavyload.0}} weight=10; }'
            - 'upstream grafana { server {{docker_host_ip}}:{{ports.grafana.0}} weight=10; }'
            - 'upstream jupyter { server {{docker_host_ip}}:{{ports.jupyter.0}} weight=10; }'
            - 'upstream netdata { server {{docker_host_ip}}:{{ports.netdata.0}} weight=10; }'
          ssl: '{{cfg_nginx_ssl_params}}'
      tags: ['`nginx']

    - import_role:
        name: dr.netdata
      vars:
        drn_allow:
          dashboard_from: '{{netdata_from}}'
          badges_from: '{{netdata_from}}'
          conf_from: '{{netdata_conf_from}}'
          connections_from: '{{netdata_streaming_from}}'
          streaming_from: '{{netdata_streaming_from}}'
        drn_stream: '{{netdata_stream_config|default({})}}'
        drn_backend: '{{netdata_backend_config|default({})}}'
      tags: ['netdata']

    - import_role:
        name: dr.clickhouse
      vars:
        chr_users_custom: '{{clickhouse_users|default([])}}'
        chr_networks_default: ["::1", "127.0.0.1", "{{ docker_net }}"]
        chr_dbs_custom: [{name: '{{clickhouse_db}}'}]
        chr_path_data: "{{dirs.clickhouse}}"
        chr_path_tmp: "{{dirs.clickhouse_tmp}}"
      tags: ['clickhouse']


    # - import_role:
    #     name: alco-openvpn-server
    #   vars:
    #     ovpn_keys_dir: '{{covpn_keys_dir}}'
    #     ovpn_docker_net_name: '{{docker_net_name}}'
    #     ovpn_docker_network: '{{docker_network}}'
    #     ovpn_docker_netmask: '{{docker_netmask}}'
    #     ovpn_port: '{{ports.openvpn.0}}'
    #   tags: ['ovpn']

    - name: Redis setup
      block:
      - import_role:
          name: dr.docker-container
        vars:
          drdc_name: "redis"
          drdc_image: "redis:4-alpine"
          drdc_network: '{{docker_net_name}}'
          drdc_memory_limit: '200m'
          drdc_volumes: ["{{dirs.redis}}:/data"]
          drdc_ports: ["{{docker_host_ip}}:{{ports.redis.0}}:{{ports.redis.1}}"]
      tags: ['redis']

    - name: CHProxy setup
      block:
      - name: Creating chproxy build directory
        tempfile:
          state: directory
          suffix: build
        register: build_dir

      - name: Rendering CHProxy configs
        template:
          src: 'chproxy/{{item}}.j2'
          dest: '{{build_dir.path}}/{{item}}'
        with_items:
          - config.yml
          - Dockerfile

      - import_role:
          name: dr.docker-container
        vars:
          drdc_name: 'chproxy'
          drdc_network: '{{docker_net_name}}'
          drdc_dir: "{{build_dir.path}}"
          drdc_memory_limit: '200m'
          drdc_ports: ["{{docker_host_ip}}:{{ports.chproxy.0}}:{{ports.chproxy.1}}"]
      tags: ['chproxy']

    - import_role:
        name: dr.docker-container
      vars:
        tmp_cmd_parts: 
          - "/opt/conda/bin/conda install jupyter -y --quiet && "
          - "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks"
          - "--ip='*' --port=8888 --no-browser --allow-root --NotebookApp.token=''"
        drdc_name: 'anaconda'
        drdc_image: "continuumio/anaconda3"
        drdc_network: '{{docker_net_name}}'
        drdc_memory_limit: '2g'
        drdc_cmd: "/bin/bash -c \"{{tmp_cmd_parts|join(' ')}}\""
        drdc_volumes: ['{{data_dir}}:/opt/notebooks']
        drdc_ports: ["{{docker_host_ip}}:{{ports.jupyter.0}}:{{ports.jupyter.1}}"]
      tags: ['anaconda']

    - name: Grafana setup
      block:
      - file:
          state: directory
          path: "{{dirs.grafana_data}}"
          owner: 472 # grafana container ids
          group: 472
      - import_role:
          name: dr.docker-container
        vars:
          drdc_name: 'grafana'
          drdc_image: "grafana/grafana"
          drdc_network: '{{docker_net_name}}'
          drdc_env:
            GF_INSTALL_PLUGINS: "{{(grafana_plugins_custom|default([]) + grafana_plugins)|join(',')}}"
            GF_AUTH_BASIC: false
            # GF_SECURITY_ADMIN_PASSWORD: secret
          drdc_memory_limit: '200m'
          drdc_volumes:
            - '{{dirs.grafana_data}}:/var/lib/grafana'
          drdc_ports:
            - "{{docker_host_ip}}:{{ports.grafana.0}}:{{ports.grafana.1}}"
      tags: ['grafana']




    - name: Heavyload setup
      block:
      - name: Creating Heavyload build directory
        tempfile:
          state: directory
          suffix: build
        register: heavyload_build

      - import_role:
          name: dr.docker-container
        vars:
          drdc_name: 'heavyload'
          drdc_network: '{{docker_net_name}}'
          drdc_env:
            WEBHOOK: "{{containers_env.KERNEL_URL}}/wh/upload/notify"
          drdc_repo: https://github.com/rockstat/heavyload
          drdc_dir: "{{heavyload_build.path}}"
          drdc_memory_limit: '200m'
          drdc_ports:
            - "{{docker_host_ip}}:{{ports.heavyload.0}}:{{ports.heavyload.1}}"
      tags: ['heavyload']

    - name: Band setup
      block:
      - import_role:
          name: dr.static-service
        vars:
          dr_name: band_collection
          dr_dir: '{{dirs.band_collection}}'
          dr_repo: https://github.com/rockstat/band-services
        tags: splash

      - import_role:
          name: dr.docker-container
        vars:
          env:
            PORT: "{{ports.band.1}}"
            IMAGES_PATH: /images
          drdc_name: 'band'
          drdc_dir: '{{dirs.band}}'
          drdc_repo: "https://github.com/rockstat/band"
          drdc_network: '{{docker_net_name}}'
          drdc_env: "{{env|combine(containers_env)}}"
          drdc_memory_limit: '300m'
          drdc_volumes:
            - "{{dirs.band_collection}}:/images/band_collection:ro"
            - "{{dirs.band}}:/images/band_base:ro"
            - "/var/run/docker.sock:/var/run/docker.sock"
          drdc_ports:
            - "{{docker_host_ip}}:{{ports.band.0}}:{{ports.band.1}}"
      tags: ['band']


    - name: Kernel setup
      block:
      - import_role:
          name: dr.docker-container
        vars:
          env:
            PORT: 8080
            PORT_WS: 8082
            PORT_WSS: 8083
            LOG_LEVEL: debug
          drdc_name: 'kernel'
          drdc_dir: "{{dirs.kernel}}"
          drdc_repo: "https://github.com/rockstat/kernel"
          drdc_network: '{{docker_net_name}}'
          drdc_env: "{{env|combine(containers_env)}}"
          drdc_memory_limit: '300m'
          drdc_volumes:
            - "{{dirs.kernel_custom_config}}:/app/config/custom"
          drdc_ports:
            - "{{docker_host_ip}}:{{ports.kernel.0}}:{{ports.kernel.1}}"
      tags: ['kernel']

