---

- name: Ensure database exists
  command: "clickhouse-client -h {{role_ops_host}} -d default"
  args:
    stdin: "CREATE DATABASE IF NOT EXISTS {{role_ops_db}} "

- name: Ensure migrations table exists
  command: "clickhouse-client -h {{role_ops_host}} -d default"
  args:
    stdin: "{{query_migrations_table}}"


- name: Running ClickHouse tasks
  include_tasks: 'run_ch_{{op.type}}.yml'
  vars:
    db: "{{role_ops_db}}"
  loop_control:
    loop_var: op
  with_items: '{{role_ops_list}}'
  when: 'role_ops_list|length > 0'
  notify:
    - restart chwriter

- name: Apply migrations folder
  include_tasks: 'run_ch_migration.yml'
  vars:
    db: "{{role_ops_db}}"
    op:
      name: "{{(item.split('/')|last).split('.')|first}}"
      file: "{{item}}"
  with_fileglob:
    - "{{role_migrations_path}}/*"