- debug:
    msg:
      - "{{op}}"
      - "{{db}}"

- name: Preparing migration {{name}}
  set_fact:
    use_name: '{{op.name|default(op.file)|splitext|first}}'
  changed_when: False

- name: Checking migration
  command: "clickhouse-client -h {{role_ops_host}} -d default"
  args:
    stdin: "SELECT name FROM {{db}}.migrations WHERE name = '{{use_name}}'"
  register: check
  changed_when: False

- name: Running migration
  command: 'clickhouse-client -h {{role_ops_host}} -d default'
  args:
    stdin: "{{query}}"
  with_items: "{{lookup('file', op.file) | from_yaml}}"
  loop_control:
    loop_var: query
  when: check.stdout == ''

- name: Saving migration info
  command: 'clickhouse-client -h {{role_ops_host}} -d default'
  args:
    stdin: "INSERT INTO {{db}}.migrations (name) VALUES('{{use_name}}')"
  when: check.stdout == ''
