    ##### ##### ##### ##### #####    OpenVPN server    ##### ##### ##### ##### ##### 
    - block:
      - debug:
          msg: "docker_net_name:{{docker_net_name}}, docker_ipnetwork:{{docker_ipnetwork}} docker_netmask:{{docker_netmask}} "
      - name: Creating vpn keys dir
        file:
          state: directory
          path: "{{dirs.ovpnkeys}}"
      - name: Including OpenVPN server role
        include_role:
          name: openvpn-server
        vars:
          ovpn_domain: "{{domain}}"
          ovpn_keys_dir: '{{dirs.ovpnkeys}}'
          ovpn_docker_net_name: '{{docker_net_name}}'
          ovpn_docker_network: '{{docker_ipnetwork}}'
          ovpn_docker_netmask: '{{docker_netmask}}'
          ovpn_port: '{{ports.openvpn.0}}'
      tags: ['never', 'ovpn']
