---
- name: Creating custom config dir
  file:
    path: '{{alco_tracker_custom_config_dir}}'
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: ['init-config']


- name: Init custom config
  template:
    src: config.yml.j2
    force: no
    dest: '{{alco_tracker_custom_config_dir}}/config.yml'
    owner: root
    group: root
    mode: 0755
  tags: ['init-config']

- name: Cloning Alcolytics tracker
  git:
    repo: https://github.com/alcolytics/alco-tracker.git
    version: '{{alco_service_version}}'
    dest: '{{alco_service_path}}'
    force: yes

- name: Building Alcolytics tracker image
  docker_image:
    force: yes
    path: '{{alco_service_path}}'
    name: alcolytics/alco-tracker
    buildargs:
      ALCOJS_VERSION: '{{alco_service_version}}'
  tags: ['tracker-rebuild']

- name: Creating Alcolytics tracker container
  docker_container:
    name: alco-tracker
    hostname: alco-tracker
    recreate: yes
    state: started
    restart: yes
    restart_policy: always
    image: alcolytics/alco-tracker
    volumes:
      - '{{alco_service_upload_store}}:/usr/src/app/upload_ch'
      - '{{alco_service_custom_configs_dir}}:/usr/src/app/config/custom'
    purge_networks: yes
    networks:
      - name: '{{alco_service_net_name}}'
    ports:
      - '{{alco_service_bind_addr}}:{{alco_service_tracker_port}}:8080'
    env:
      CH_DSN: "http://{{alco_docker_ip}}:{{alco_ch_port}}/{{alco_db_name}}"
      STATSD_HOST: '{{alco_docker_ip}}'
      SXGEO_SERVICE: geoip-sypex:8080
      DEVICED_SERVICE: devicedetector:8080
      MIXPANEL_TOKEN: "{{mixpanel_token|default('')}}"
      LOG_LEVEL: '{{alco_service_log_level}}'
  tags: ['tracker-rebuild']

