---
- name: Cloning Alcolytics tracker
  git:
    repo: https://github.com/alcolytics/alco-tracker.git
    force: yes
    version: '{{alco_service_version}}'
    dest: '{{alco_service_path}}'


- name: Building Alcolytics tracker image
  docker_image:
    force: yes
    path: '{{alco_service_path}}'
    name: alcolytics/alco-tracker
    buildargs:
      ALCOJS_VERSION: '{{alco_service_version}}'


- name: Creating Alcolytics tracker container
  docker_container:
    name: alco-tracker
    hostname: alco-tracker
    recreate: yes
    state: started
    restart: yes
    restart_policy: always
    image: alcolytics/alco-tracker
    volumes:
      - /srv/upload_ch:/usr/src/app/upload_ch
      - ~/custom-config:/usr/src/app/config/custom
    purge_networks: yes
    networks:
      - name: '{{alco_service_net_name}}'
    ports:
      - '{{alco_service_bind_addr}}:{{alco_service_tracker_port}}:8080'
    env:
      CH_DSN: "http://{{alco_docker_ip}}:{{alco_ch_port}}/{{alco_db_name}}"
      STATSD_HOST: '{{alco_docker_ip}}'
      SXGEO_SERVICE: geoip-sypex:8080
      DEVICED_SERVICE: devicedetector:8080
      MIXPANEL_TOKEN: "{{mixpanel_token|default('')}}"
#      DEBUG: "*"

