---
- name: Setting variables
  set_fact:
    chproxy_docker_bind_addr: '{{chproxy_docker_bind_addr|default(chproxy_docker_bind_addr_default)}}'
    chproxy_port: '{{chproxy_port|default(chproxy_port_default)}}'

- name: Cloning CHProxy Dockerfile
  git:
    repo: https://github.com/alcolytics/alco-chproxy
    dest: ./alco-chproxy

- name: Creating config
  template:
   src: config.yml.j2
   dest: './alco-chproxy/config.yml'

- name: Building CHProxy image
  docker_image:
    path: ./alco-chproxy
    name: alcolytics/chproxy
    force: yes

- name: Creating CHProxy container
  docker_container:
    name: chproxy
    hostname: chproxy
    recreate: yes
    state: started
    restart: yes
    restart_policy: always
    image: alcolytics/chproxy
    purge_networks: yes
    networks:
      - name: '{{chproxy_docker_net_name}}'
    ports:
      - '{{chproxy_docker_bind_addr}}:{{chproxy_port}}:9090'
