---
- name: Cloning CHProxy Dockerfile
  git:
    repo: '{{chproxy_repo}}'
    dest: '{{chproxy_build_path}}'
  when: chproxy_repo is defined

- name: Checking build exists
  file:
    path: '{{chproxy_build_path}}'
    state: directory

- name: Rendering CHProxy files
  template:
    src: '{{item}}.j2'
    dest: '{{chproxy_build_path}}/{{item}}'
  with_items:
    - config.yml
    - Dockerfile

- name: Building CHProxy docker image
  docker_image:
    path: '{{chproxy_build_path}}'
    name: '{{chproxy_docker_image}}'
    force: yes

- name: Removing old container
  docker_container:
    name: chproxy
    state: absent

- name: Creating and starting CHProxy docker container
  docker_container:
    name: '{{chproxy_container}}'
    hostname: '{{chproxy_container}}'
    recreate: yes
    state: started
    restart: yes
    restart_policy: always
    image: '{{chproxy_docker_image}}'
    purge_networks: yes
    networks: '{{chproxy_docker_networks}}'
    ports:
      - '{{chproxy_docker_expose}}:{{chproxy_internal_port}}'
