---
- name: Setting variables
  set_fact:
    chproxy_docker_bind_addr: '{{chproxy_docker_bind_addr}}'
    chproxy_port: '{{chproxy_port}}'

- name: Cloning CHProxy Dockerfile
  git:
    repo: https://github.com/alcolytics/alco-chproxy
    dest: '{{chproxy_clone_to}}'

- name: Creating config
  template:
   src: config.yml.j2
   dest: '{{chproxy_clone_to}}/config.yml'

- name: Building CHProxy image
  docker_image:
    path: '{{chproxy_clone_to}}'
    name: alcolytics/chproxy
    force: yes

- name: Creating CHProxy container
  docker_container:
    name: chproxy
    hostname: chproxy
    recreate: yes
    state: started
    restart: yes
    restart_policy: always
    image: alcolytics/chproxy
    purge_networks: yes
    networks:
      - name: '{{chproxy_docker_net_name}}'
    ports:
      - '{{chproxy_docker_bind_addr}}:{{chproxy_port}}:9090'
