---
# ########## Nginx ##########
_nginx_gzip_params:
  - gzip on
  - gzip_min_length 10240
  - gzip_proxied expired no-cache no-store private auth
  - gzip_types text/plain text/css text/javascript application/javascript application/x-javascript
_nginx_ssl_params:
  - ssl_session_cache shared:SSL:10m
  - ssl_session_timeout 10m
  - ssl_prefer_server_ciphers on
  - ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5
  - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
  - ssl_stapling on
  - ssl_stapling_verify on
_nginx_http_params:
  - tcp_nopush on
  - tcp_nodelay on
  - keepalive_timeout 60
  - keepalive_requests 1000
  - error_log /var/log/nginx/error.log
  - access_log /var/log/nginx/access.log
  # - access_log off
_nginx_proxy_params:
  - proxy_redirect   off
  - proxy_buffering  off
  - proxy_http_version 1.1
  - proxy_set_header Host            $host
  - proxy_set_header X-Real-IP       $remote_addr
  - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
_nginx_proto_upgrade:
  - map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

# ########## Grafana ##########
grafana_plugins:
  - grafana-clock-panel
  - grafana-simple-json-datasource
  - vertamedia-clickhouse-datasource
  - grafana-piechart-panel
  - petrslavotinek-carpetplot-panel
  - jdbranham-diagram-panel
  - raintank-worldping-app
  - ryantxu-ajax-panel
  - natel-discrete-panel
# use this variable in your private config
# grafana_plugins_custom:
  # - plugin that i want

# ########## Other things ##########

hostname: "{{inventory_hostname_short|default(inventory_hostname)}}"

# ########## Mailer config ##########
mailer_subj_key: "Ваши ключи OpenVPN ({{ domain }}) v{{ playbook_version }}"
mailer_subj_snip: "Сниппет для сайта ({{ domain }}) v{{ playbook_version }}"


