alco_service_net_name: bridge
alco_service_bind_addr: 127.0.0.1
alco_service_tracker_port: 8081
alco_service_path: ./alco-tracker
alco_service_version: master
alco_service_upload_store: /srv/upload_ch
alco_service_custom_configs_dir: ~/custom-config
alco_service_log_level: info
