---
- name: Dependencies
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - sudo
    - python-pip
    - python-pkg-resources
    - python-setuptools
    - gzip
    - unzip
    - curl
    - apt-transport-https
    - openssl
    - tzdata
    - nano

- name: Locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Updating locale
  command: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
  changed_when: false

- name: Seting timezone to UTC
  timezone:
    name: Etc/UTC
  ignore_errors: yes

- name: Installing ntp
  apt: name=ntp state=present

- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='.*\#ansible_line$' line='127.0.0.1    {{ inventory_hostname_short|default(inventory_hostname) }} \#ansible_line' state=present
  tags: ['hostname']

- name: Changing hostname to match inventory_hostname_short
  hostname:
    name: "{{ inventory_hostname_short|default(inventory_hostname) }}"
  register: "hostname_status"
  when: ansible_hostname != inventory_hostname_short|default(inventory_hostname)
  ignore_errors: yes
  tags: ['hostname']

- include_tasks: user.yml
  when: setup_user == True and use_user is defined
  tags: ['user']

- import_tasks: ufw.yml
  when: setup_ufw == True
  tags: ['ufw']

