- name: Creating user
  user:
    name: '{{ use_user }}'
    password: '{{ use_pass|default(omit) }}'
    ssh_key_type: '.ssh/id_rsa'
    groups: sudo
    shell: /bin/bash

- name: Adding SSH keys
  authorized_key:
    user: '{{ use_user }}'
    state: present
    key: '{{ item }}'
  with_file:
    - '{{use_key_file}}'
  when: use_key_file is defined and use_key_file != ''

- name: Adding to sudoers
  lineinfile: dest='/etc/sudoers' state='present' regexp='^{{use_user}} ' line='{{use_user}} ALL=(ALL:ALL) NOPASSWD:ALL'
