---
- name: Cloning GeoIP Sypex
  git:
    repo: https://github.com/alcolytics/alco-geoip-sypex
    dest: '{{alco_service_clone_to}}/alco-geoip-sypex'


- name: Cloning Device Detector
  git:
    repo: https://github.com/alcolytics/alco-devicedetector
    dest: '{{alco_service_clone_to}}/alco-devicedetector'


- name: Building GeoIP Sypex image
  docker_image:
    path: '{{alco_service_clone_to}}/alco-geoip-sypex'
    name: alcolytics/geoip-sypex
    force: yes


- name: Building Device Detector image
  docker_image:
    path: '{{alco_service_clone_to}}/alco-devicedetector'
    name: alcolytics/devicedetector
    force: yes


- name: Creating GeoIP Sypex container
  docker_container:
    name: geoip-sypex
    hostname: geoip-sypex
    recreate: yes
    state: started
    restart: yes
    restart_policy: always
    image: alcolytics/geoip-sypex
    purge_networks: yes
    networks:
      - name: '{{alco_service_net_name}}'
    ports:
      - '{{alco_service_bind_addr}}:{{alco_service_geoip_port}}:8080'


- name: Creating Device Detector container
  docker_container:
    name: devicedetector
    hostname: devicedetector
    recreate: yes
    state: started
    restart: yes
    restart_policy: always
    image: alcolytics/devicedetector
    purge_networks: yes
    networks:
      - name: '{{alco_service_net_name}}'
    ports:
      - '{{alco_service_bind_addr}}:{{alco_service_deviced_port}}:8080'
