---

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  tags: [always]

- import_tasks: nginx-official-repo.yml
  tags: [packages, nginx]

- name: Install the nginx packages for all other distributions
  apt:
    name: '{{item}}'
    state: latest
    update_cache: yes
  with_items: "{{ nginx_pkgs }}"
  environment: "{{ nginx_env }}"

- import_tasks: ensure-dirs.yml
  tags: [configuration, nginx]

- import_tasks: remove-defaults.yml
  when: not keep_only_specified
  tags: [configuration, nginx]

- import_tasks: remove-extras.yml
  when: keep_only_specified
  tags: [configuration, nginx]

- import_tasks: remove-unwanted.yml
  tags: [configuration, nginx]

- import_tasks: configuration.yml
  tags: [configuration, nginx]

- name: Start the nginx service
  service: name={{ nginx_service_name }} state=started enabled=yes
  when: nginx_installation_type in nginx_installation_types_using_service and nginx_daemon_mode == "on"
  tags: [service, nginx]
