---
- name: Ensure APT official nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key
  environment: "{{ nginx_env }}"

- name: Ensure APT official nginx repository
  apt_repository: repo="deb http://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
  environment: "{{ nginx_env }}"

