
- name: Sending client cert to email
  command: >
    curl -s --user 'api:{{amail_mailgun_key}}' https://api.mailgun.net/v3/alcolytics.ru/messages
        -F from={{amail_sender|quote}}
        -F to={{amail_to|quote}}
        -F subject={{amail_subj_key|quote}}
        -F text={{lookup('template', 'vpn_email.j2')|quote}}
        -F attachment=@{{amail_ovpn_keys_dir}}/vpn_user1.ovpn
        -F attachment=@{{amail_ovpn_keys_dir}}/vpn_user2.ovpn
        -F attachment=@{{amail_ovpn_keys_dir}}/vpn_user3.ovpn
        -F attachment=@{{amail_ovpn_keys_dir}}/vpn_user4.ovpn
        -F attachment=@{{amail_ovpn_keys_dir}}/vpn_user5.ovpn
  when: amail_mailgun_key is defined and amail_enabled == 'yes'
  args:
    warn: false
  tags: ['ovpn']


- set_fact:
    snippet: "{{ lookup('template', 'snippet.j2') }}"
  tags: ['tracker_email']


- name: Sending email with snippet
  command: |
    curl -s --user 'api:{{amail_mailgun_key}}' https://api.mailgun.net/v3/alcolytics.ru/messages
        -F from={{amail_sender|quote}}
        -F to={{amail_to|quote}}
        -F subject={{amail_subj_snip|quote}}
        -F text={{ snippet|quote }}
  when: amail_mailgun_key is defined and amail_enabled == 'yes'
  args:
    warn: false
  tags: ['tracker']
