# Use temp dir id build dir not provided

- block:
  - set_fact:
      chproxy_build_path: "{{chproxy_build_dir}}/{{chproxy_container}}"
    when: chproxy_build_dir is defined
  when: chproxy_build_path is not defined

- file:
    state: directory
    path: "{{chproxy_build_path}}"
  when: chproxy_build_path is defined

- name: Creating chproxy build directory
  block:
  - tempfile:
      state: directory
      suffix: build
    register: tmp_dir
  - set_fact:
      chproxy_build_path: "{{tmp_dir.path}}"
  when: chproxy_build_path is not defined

- name: Rendering CHProxy configs
  template:
    src: '{{item}}.j2'
    dest: '{{chproxy_build_path}}/{{item}}'
  with_items:
    - config.yml
    - Dockerfile

- include_role:
    name: dr.docker-container
  vars:
    drdc_name: "{{chproxy_container}}"
    drdc_network: '{{chproxy_docker_net}}'
    drdc_dir: "{{chproxy_build_path}}"
    drdc_purge_networks: yes
    drdc_memory_limit: '200m'
    drdc_ports: ["{{chproxy_docker_bind}}"]
