---

- debug:
    msg: 'alco_docker_user:{{alco_docker_user}} alco_docker_net_name:{{alco_docker_net_name}} alco_docker_interface:{{alco_docker_interface}} alco_docker_net:{{alco_docker_net}}'

- name: Adding Docker key
  apt_key: >
    keyserver="hkp://p80.pool.sks-keyservers.net:80"
    id="58118E89F3A912897C070ADBF76221572C52609D"

- name: Adding Docker repo
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    state: present

- name: Updating apt repos
  apt: update_cache=yes

- name: Installing docker
  apt: name=docker-engine state=present


- name: Removing old lib
  pip:
    name: '{{item}}'
    state: absent
  with_items:
    - docker-py
    - docker-pycreds
    - docker

- name: Installing docker
  pip:
    name: docker
    version: '2.7.0'

- name: Creating docker network
  docker_network:
    name: '{{ alco_docker_net_name }}'
    driver_options:
      com.docker.network.bridge.name: '{{ alco_docker_interface }}'
    ipam_options:
      subnet: "{{ alco_docker_net }}"
  when: alco_docker_create_network == True

- name: Adding action user to docker group
  user:
    name: "{{alco_docker_user}}"
    groups:
      - docker
    append: yes
  when: alco_docker_user != 'root'
